slam_toolbox:
  ros__parameters:
    solver_plugin: solver_plugins::CeresSolver

    odom_frame: odom
    map_frame: map
    base_frame: base_link        # <---- CORREGIDO

    scan_topic: /scan
    use_map_saver: false
    mode: mapping

    debug_logging: false
    throttle_scans: 1

    # PUBLICACIÓN DE TF MUY RÁPIDA
    transform_publish_period: 0.005

    # PROCESA CADA SCAN
    minimum_travel_distance: 0.0
    minimum_travel_heading: 0.0

    # AUMENTAMOS EL TAMAÑO DEL BUFFER
    scan_buffer_size: 100
    scan_buffer_maximum_scan_distance: 10.0

    # Cosas que ayudan al C1:
    max_laser_range: 12.0
    min_laser_range: 0.02

    loop_search_maximum_distance: 3.0
    do_loop_closing: true
